# Generated by Django 4.1 on 2022-08-25 12:18

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdocuments',
            name='creamcertificate',
            field=models.FileField(default=None, upload_to=api.models.StudentDocuments.use_directory_path),
        ),
        migrations.AddField(
            model_name='studentdocuments',
            name='crname',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
