# Generated by Django 4.1 on 2022-08-22 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdocuments',
            name='auid',
            field=models.CharField(default=None, max_length=4),
        ),
    ]
