# Generated by Django 4.1 on 2022-08-24 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdocuments',
            name='icincome',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
