# Generated by Django 4.1 on 2022-08-21 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetails',
            name='nsp_id',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='pms_benificiary_id',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
