# Generated by Django 4.1 on 2022-08-16 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_studentdocuments_sid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdocuments',
            name='aadhar',
            field=models.FileField(default=True, max_length=250, upload_to=''),
        ),
        migrations.AlterField(
            model_name='studentdocuments',
            name='incomecertificate',
            field=models.FileField(default=True, max_length=250, upload_to=''),
        ),
    ]
