# Generated by Django 4.1 on 2022-08-24 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_studentdocuments_icincome'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='refreshtoken',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
