# Generated by Django 4.1 on 2022-08-24 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_refreshtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdocuments',
            name='refreshtoken',
            field=models.BooleanField(default=False),
        ),
    ]
