# Generated by Django 4.1 on 2022-08-17 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_studentdocuments_aadhar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdetails',
            name='email',
        ),
        migrations.RemoveField(
            model_name='studentdetails',
            name='password',
        ),
    ]
