# Generated by Django 4.0.6 on 2022-07-20 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_formdetails_aadhaar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetails',
            name='caste_category',
            field=models.CharField(choices=[('sc', 'SC'), ('obc', 'OBC')], default='--Select--', max_length=20),
        ),
    ]
