# Generated by Django 4.1 on 2022-08-18 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_studentdetails_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdocuments',
            name='aadhar',
            field=models.CharField(default=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='studentdocuments',
            name='incomecertificate',
            field=models.CharField(default=True, max_length=250),
        ),
    ]
