# Generated by Django 4.1 on 2022-08-12 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_studentdetails_caste_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aadhar', models.FileField(upload_to='uploads/')),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.studentdetails')),
            ],
        ),
    ]
