# Generated by Django 4.1 on 2022-08-14 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_studentdetails_nsp_id_radio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdocuments',
            name='id',
        ),
        migrations.AddField(
            model_name='studentdocuments',
            name='incomecertificate',
            field=models.FileField(default=True, max_length=250, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='studentdocuments',
            name='aadhar',
            field=models.FileField(default=True, max_length=250, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='studentdocuments',
            name='sid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.studentdetails'),
        ),
    ]
