# Generated by Django 4.1 on 2022-08-18 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_studentdocuments_aadhar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdocuments',
            name='aadhar',
            field=models.CharField(default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='studentdocuments',
            name='incomecertificate',
            field=models.CharField(default=None, max_length=250, null=True),
        ),
    ]
