# Generated by Django 4.1 on 2022-08-19 17:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_studentdocuments_aadhar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdocuments',
            name='adob',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentdocuments',
            name='agender',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentdocuments',
            name='aname',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='family_income',
            name='sid',
            field=models.OneToOneField(db_column='sid', default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='formdetails',
            name='sid',
            field=models.OneToOneField(db_column='sid', default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
